//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPet()
        {
            this.TPetImages = new HashSet<TPetImage>();
            this.TVisits = new HashSet<TVisit>();
        }
    
        public int intPetID { get; set; }
        public string strPetNumber { get; set; }
        public string strMicrochipID { get; set; }
        public string strPetName { get; set; }
        public int intPetTypeID { get; set; }
        public int intGenderID { get; set; }
        public int intBreedID { get; set; }
        public System.DateTime dtmDateofBirth { get; set; }
        public double dblWeight { get; set; }
        public bool isBlind { get; set; }
        public bool isDeaf { get; set; }
        public bool isAggressive { get; set; }
        public bool isDeceased { get; set; }
        public bool isAllergic { get; set; }
        public string strColor { get; set; }
        public string strNotes { get; set; }
        public int intOwnerID { get; set; }
    
        public virtual TBreed TBreed { get; set; }
        public virtual TGender TGender { get; set; }
        public virtual TOwner TOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPetImage> TPetImages { get; set; }
        public virtual TPetType TPetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisit> TVisits { get; set; }
		public TPetImage TPetImage { get; internal set; }
	}
}
